// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformDemo.Data.Data;

#nullable disable

namespace PlatformDemo.Data.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20241007154650_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlatformDemo.Data.Models.ServicePlan", b =>
                {
                    b.Property<int>("ServicePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicePlanId"));

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.HasKey("ServicePlanId");

                    b.ToTable("ServicePlans");

                    b.HasData(
                        new
                        {
                            ServicePlanId = 1,
                            DateOfPurchase = new DateTime(2024, 6, 29, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4590)
                        },
                        new
                        {
                            ServicePlanId = 2,
                            DateOfPurchase = new DateTime(2024, 8, 18, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4605)
                        },
                        new
                        {
                            ServicePlanId = 3,
                            DateOfPurchase = new DateTime(2024, 9, 12, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4606)
                        },
                        new
                        {
                            ServicePlanId = 4,
                            DateOfPurchase = new DateTime(2024, 9, 27, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4607)
                        },
                        new
                        {
                            ServicePlanId = 5,
                            DateOfPurchase = new DateTime(2024, 10, 2, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4608)
                        });
                });

            modelBuilder.Entity("PlatformDemo.Data.Models.Timesheet", b =>
                {
                    b.Property<int>("TimesheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimesheetId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServicePlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TimesheetId");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("Timesheets");

                    b.HasData(
                        new
                        {
                            TimesheetId = 1,
                            Description = "Timesheet 1 for ServicePlan 1",
                            EndTime = new DateTime(2024, 7, 1, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4775),
                            ServicePlanId = 1,
                            StartTime = new DateTime(2024, 6, 30, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4774)
                        },
                        new
                        {
                            TimesheetId = 2,
                            Description = "Timesheet 2 for ServicePlan 1",
                            EndTime = new DateTime(2024, 7, 10, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4777),
                            ServicePlanId = 1,
                            StartTime = new DateTime(2024, 7, 9, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4776)
                        },
                        new
                        {
                            TimesheetId = 3,
                            Description = "Timesheet 1 for ServicePlan 2",
                            EndTime = new DateTime(2024, 8, 20, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4778),
                            ServicePlanId = 2,
                            StartTime = new DateTime(2024, 8, 19, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4778)
                        },
                        new
                        {
                            TimesheetId = 4,
                            Description = "Timesheet 1 for ServicePlan 3",
                            EndTime = new DateTime(2024, 9, 18, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4780),
                            ServicePlanId = 3,
                            StartTime = new DateTime(2024, 9, 17, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4779)
                        },
                        new
                        {
                            TimesheetId = 5,
                            Description = "Timesheet 1 for ServicePlan 4",
                            EndTime = new DateTime(2024, 9, 29, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4782),
                            ServicePlanId = 4,
                            StartTime = new DateTime(2024, 9, 28, 23, 46, 50, 403, DateTimeKind.Local).AddTicks(4781)
                        });
                });

            modelBuilder.Entity("PlatformDemo.Data.Models.Timesheet", b =>
                {
                    b.HasOne("PlatformDemo.Data.Models.ServicePlan", "ServicePlan")
                        .WithMany("Timesheets")
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("PlatformDemo.Data.Models.ServicePlan", b =>
                {
                    b.Navigation("Timesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
